// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-NwANG2Q2X9meOMdjQfswL82-Gz9eDwo',
    appId: '1:654619781138:web:1ec2d640f31c62277e50cb',
    messagingSenderId: '654619781138',
    projectId: 'tablelab-ab615',
    authDomain: 'tablelab-ab615.firebaseapp.com',
    storageBucket: 'tablelab-ab615.firebasestorage.app',
    measurementId: 'G-H4D9DBVXDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjrGBBXHdDffB28T1PSEoK5LC5z7fcgI',
    appId: '1:654619781138:android:35cb8f05aee61bde7e50cb',
    messagingSenderId: '654619781138',
    projectId: 'tablelab-ab615',
    storageBucket: 'tablelab-ab615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPU8-8W-sz7I_Lxyv_hGqNIprhZNkmMI',
    appId: '1:654619781138:ios:1304e58fbe83fea27e50cb',
    messagingSenderId: '654619781138',
    projectId: 'tablelab-ab615',
    storageBucket: 'tablelab-ab615.firebasestorage.app',
    iosBundleId: 'com.pokertracker.pokerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdPU8-8W-sz7I_Lxyv_hGqNIprhZNkmMI',
    appId: '1:654619781138:ios:1304e58fbe83fea27e50cb',
    messagingSenderId: '654619781138',
    projectId: 'tablelab-ab615',
    storageBucket: 'tablelab-ab615.firebasestorage.app',
    iosBundleId: 'com.pokertracker.pokerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-NwANG2Q2X9meOMdjQfswL82-Gz9eDwo',
    appId: '1:654619781138:web:85bc1aa93f95f1bd7e50cb',
    messagingSenderId: '654619781138',
    projectId: 'tablelab-ab615',
    authDomain: 'tablelab-ab615.firebaseapp.com',
    storageBucket: 'tablelab-ab615.firebasestorage.app',
    measurementId: 'G-0KF5Q7HNQX',
  );
}
