// This file is generated by FlutterFire CLI.
// Run the following after completing Firebase console setup:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command will overwrite this file with your real project credentials
// and update android/app/google-services.json automatically.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace this file by running: flutterfire configure
    throw UnsupportedError(
      'firebase_options.dart has not been generated yet. '
      'Run: dart pub global activate flutterfire_cli && flutterfire configure',
    );
  }
}
